version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    restart: unless-stopped

volumes:
  backend_data:

networks:
  default:
    name: indie-story-network
